version: '3.8'

services:
  shadowsocks:
    image: shadowsocks/shadowsocks-libev:latest
    container_name: shadowsocks-client
    restart: unless-stopped
    command: >
      ss-local
      -s 82.97.246.158
      -p 25432
      -l 1080
      -k EBZOsyGa1XFmnjHe3BaD0U
      -m chacha20-ietf-poly1305
      -b 0.0.0.0
      -v
    networks:
      - bot_network
    healthcheck:
      test: ["CMD", "ss-local", "-h"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: pgvector/pgvector:pg16
    container_name: immigration_bot_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-botuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_USER:-botuser}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bot_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-botuser} -d ${POSTGRES_USER:-botuser}"]
      interval: 10s
      timeout: 5s
      retries: 5

  bot:
    build: .
    container_name: immigration_bot
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      shadowsocks:
        condition: service_started
    environment:

      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      ADMIN_TELEGRAM_IDS: ${ADMIN_TELEGRAM_IDS}
      

      DATABASE_URL: postgresql://${POSTGRES_USER:-botuser}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_USER:-botuser}
      

      LLM_PROVIDER: ${LLM_PROVIDER:-openai}
      
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_MODEL: ${OPENAI_MODEL:-gpt-4o-mini}
      OPENAI_EMBEDDING_MODEL: ${OPENAI_EMBEDDING_MODEL:-text-embedding-3-small}
      
      
      CONFIDENCE_THRESHOLD: ${CONFIDENCE_THRESHOLD:-0.7}

      TAVILY_API_KEY: ${TAVILY_API_KEY}
      
      SHADOWSOCKS_PROXY: socks5://shadowsocks:1080
      
    networks:
      - bot_network
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data

networks:
  bot_network:
    driver: bridge

volumes:
  postgres_data: